services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/processor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - processor
  php:
    build: docker/php
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./:/processor
    networks:
      - processor

networks:
  processor: